version: '3'
#
# Create a common network for all services.
networks:
  rhinonetwork:
    name: rhinonetwork

services:
  #
  # Deploy rhino service
  rhino:
    image: rhinoapi/rhino-agent:latest
    networks:
      rhinonetwork: null
    restart: unless-stopped
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - /C/DockerVolumes/Rhino/Outputs:/app/Outputs
      - /C/DockerVolumes/Rhino/Data:/app/Data
      - /C/DockerVolumes/Rhino/Plugins:/app/Plugins
  #
  # Deploy selenoid service.
  selenoid:
    networks:
      rhinonetwork: null
    image: aerokube/selenoid:latest-release
    restart: unless-stopped
    volumes:
      - "/app/rhino/volumes/seleniod:/etc/selenoid"
      - "/app/rhino/volumes/seleniod/video:/opt/selenoid/video"
      - "/app/rhino/volumes/seleniod/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/app/rhino/volumes/seleniod/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "rhinonetwork"]
    ports:
      - "4444:4444"
  #
  # Deploy selenoid-ui service and link to selenoid backend
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    networks:
      rhinonetwork: null
    restart: unless-stopped
    depends_on:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  #
  # Deploy openproject application
  openproject:
    image: openproject/community:11
    networks:
      rhinonetwork: null
    restart: unless-stopped
    environment:
      - SECRET_KEY_BASE=secret
    ports:
      - 8085:80
  #
  # Deploy elastic engine
  elasticsearch:
    image: elasticsearch:7.14.2
    networks:
      rhinonetwork: null
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - /app/rhino/volumes/elastic:/usr/share/elasticsearch/data
  #
  # Deploy kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    networks:
      rhinonetwork: null
    restart: unless-stopped
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - /app/rhino/volumes/kibana:/usr/share/kibana/data
